name: "Build"
on:
  workflow_call:
    inputs:
      package-name: #e.g.: network
        required: true
        type: string
    secrets:
      BUILD_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: packages/${{ inputs.package-name }}
    env:
      BUILD_TOKEN: ${{ secrets.BUILD_TOKEN }}
    steps:
      - name: Checkout oscd-plugins/main
        uses: actions/checkout@v3
        
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      
      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Dependencies
        run: pnpm install 
  
      - name: Build Plugin
        # run: pnpm -C ./packages/${{ inputs.package-name }} run build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        # If you're changing the branch from main,
        # also change the `main` in `refs/heads/main`
        # below accordingly.
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # publish_dir: dist
          publish_dir: packages/${{ inputs.package-name }}/dist
          destination_dir: packages/${{inputs.package-name}}

      # - name: Deploy to GitHub Pages
      #   run: |
      #     git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
      #     npx gh-pages --dist dist --dest packages/${{inputs.package-name}} --dotfiles -u "github-actions-bot <support+actions@github.com>"
      #   env:
      #     # BUILD_TOKEN: ${{ secrets.BUILD_TOKEN }}
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
